kind: pipeline
name: default

trigger:
  branch:
    - main

load: yes

steps:
  - name: build
    image: maven:3-eclipse-temurin-16
    commands:
      - mvn package --no-transfer-progress -DskipTests=true -Dmaven.javadoc.skip=true -B -V


  - name: test
    image: maven:3-eclipse-temurin-16
    commands:
      - mvn test --no-transfer-progress -B

  - name: code-analysis
    image: maven:3-eclipse-temurin-16
    commands:
      - mvn sonar:sonar --no-transfer-progress -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.host.url=$SONAR_INSTANCE_URL -Dsonar.login=$SONAR_LOGIN_KEY
    environment:
      SONAR_PROJECT_KEY:
        from_secret: sonar_project_key
      SONAR_INSTANCE_URL:
        from_secret: sonar_instance_url
      SONAR_LOGIN_KEY:
        from_secret: sonar_login_key

  - name: maven-auth
    image: robertstettner/drone-mvn-auth
    pull: true
    servers:
      - id: nexus
        username: ${NEXUS_USERNAME}
        password: ${NEXUS_PASSWORD}
    profiles:
      - id: default
        repositories:
          - id: nexus-releases
            name: Nexus Releases
            url: https://nexus.beatrice.wtf/repository/maven-releases/
            layout: default
    active_profiles:
      - default
    when:
      event:
        - promote
      target:
        - production

  - name: maven-deploy
    image: maven:3-eclipse-temurin-16
    commands:
      - mvn deploy --no-transfer-progress -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    when:
      event:
        - promote
      target:
        - production