kind: template
load: java-build-deploy.yaml
data:
  arch: arm64
  os: linux
  build_branches:
    - main
    - develop
  build_events:
    - push
    - pull_request
  sonar_project_key: HidekoBot
  deploy_targets:
    - production
