kind: pipeline
name: default

trigger:
  branch:
    - main

steps:
  - name: build
    image: maven:3-eclipse-temurin-16
    commands:
      - mvn install --no-transfer-progress -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn javadoc:javadoc
      - mvn test -B

  - name: code-analysis
    image: maven:3-eclipse-temurin-16
    commands:
      - mvn sonar:sonar --no-transfer-progress -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.host.url=$SONAR_INSTANCE_URL -Dsonar.login=$SONAR_LOGIN_KEY
    environment:
      SONAR_PROJECT_KEY:
        from_secret: sonar_project_key
      SONAR_INSTANCE_URL:
        from_secret: sonar_instance_url
      SONAR_LOGIN_KEY:
        from_secret: sonar_login_key