kind: pipeline
name: default

trigger:
  branch:
    - main

load: yes

steps:


  - name: maven-auth
    image: robertstettner/drone-mvn-auth
    pull: true
    servers:
      from_secret: maven_servers
    profiles:
      - id: default
        repositories:
          - id: nexus-releases
            name: Nexus Releases
            url: https://nexus.beatrice.wtf/repository/maven-releases/
            layout: default
    active_profiles:
      - default
    when:
      event:
        - promote
      target:
        - production

  - name: maven-deploy
    image: maven:3-eclipse-temurin-16
    commands:
      - cat settings.xml
      - mvn deploy --no-transfer-progress -DskipTests=true -Dmaven.javadoc.skip=true -B -V -gs settings.xml
    when:
      event:
        - promote
      target:
        - production