kind: pipeline
name: default

trigger:
  branch:
    - main

steps:
  - name: build
    image: maven:3-eclipse-temurin-16
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn javadoc:javadoc
      - mvn test -B
