kind: pipeline
name: default

trigger:
  branch:
    - main

load: yes

steps:


  - name: maven-deploy
    image: maven:3-eclipse-temurin-16
    commands:
      - mvn deploy --no-transfer-progress -DskipTests=true -Dmaven.javadoc.skip=true -B -V -gs settings.xml -Dmaven.repo.username=$MAVEN_REPO_USERNAME -Dmaven.repo.password=$MAVEN_REPO_PASSWORD
    environment:
      MAVEN_REPO_USERNAME:
        from_secret: maven_repo_username
      MAVEN_REPO_PASSWORD:
        from_secret: maven_repo_password
    when:
      event:
        - promote
      target:
        - production